- id: '1544890965790'
  alias: New Automation
  trigger:
  - entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    platform: state
    to: '1'
  condition: []
  action:
  - service: notify.mypushbullet


- alias: ColemanInBed
  trigger:
    platform: state
    entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    to: 'on'
  action:
    service: notify.mypushbullet
    data_template:
      title: "Coleman Bed Sensor"
      message: "Coleman in bed"

- alias: ColemanOutBed
  trigger:
    platform: state
    entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    to: 'off'
  action:
    service: notify.mypushbullet
    data_template:
      title: "Coleman Bed Sensor"
      message: "Coleman out of bed"


#--------------------------------------------------

#fuckin around with lights

- alias: Turn on kitchen light when there is movement
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_sensor
    to: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.kitchen
        brightness: 255
- alias: Turn off kitchen light 1 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_sensor
    to: 'off'
    for:
      minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: light.kitchen
    data: 
      transition: 7

# You can also restrict lights from turning on based on 
#   time of day and implement transitions for 
#   fading lights on and off.


# Here is Bedroom Lights: 
#    Turn on with Hue sensor bright unless either person in bed

- alias: Bedroom Lights Sensor Awake Time
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00:00'
        before: '23:00:00'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
        state: 'off'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_liz_is_in_bed
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.bedroom

- alias: Bedroom Lights Sensor Awake Time
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00:00'
        before: '23:00:00'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
        state: 'off'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_liz_is_in_bed
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.bedroom
- alias: Turn off bedroom light 1 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'off'
    for:
      minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: light.bedroom
    data: 
      transition: 4
