- id: '1544890965790'
  alias: New Automation
  trigger:
  - entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    platform: state
    to: '1'
  condition: []
  action:
  - service: notify.mypushbullet


- alias: ColemanInBed
  trigger:
    platform: state
    entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    to: 'on'
  action:
    service: notify.mypushbullet
    data_template:
      title: "Coleman Bed Sensor"
      message: "Coleman in bed"

- alias: ColemanOutBed
  trigger:
    platform: state
    entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    to: 'off'
  action:
    service: notify.mypushbullet
    data_template:
      title: "Coleman Bed Sensor"
      message: "Coleman out of bed"


#--------------------------------------------------

#fuckin around with lights

- alias: Turn on kitchen light when there is movement
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_sensor
    to: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.kitchen
        brightness: 255
- alias: Turn off kitchen light 1 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_sensor
    to: 'off'
    for:
      minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: light.kitchen
    data: 
      transition: 7

# You can also restrict lights from turning on based on 
#   time of day and implement transitions for 
#   fading lights on and off.


# Here is Bedroom Lights: 
#    Turn on with Hue sensor bright unless either person in bed

# Bed Daytime - full bright with motion
#    Turn on lights full bright between 7am and 11 pm
#    and if bed is empty
- alias: Bedroom Sensor Day Time
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '06:30:00'
        before: '23:00:00'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
        state: 'off'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_liz_is_in_bed
        state: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.bedroom
        brightness: 255

# Bed Nighttime - underbed dim with motion
#    Turn on lights full bright between 9pm and 6:30 am
#    and if at least 1 person in bed
#    and if bed lights were off
- alias: Bedroom Sensor Day Time
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00:00'
        before: '06:30:00'
      - condition: state
        entity_id: light.under_bed_lightstrip
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
          state: 'on'
        - condition: state
          entity_id: binary_sensor.sleepnumber_m7_liz_is_in_bed
          state: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.under_bed_lightstrip
        rgb_color: [255,0,0]
        brightness: 5

- alias: Bedroom light OFF 1 minutes after last movement if bed empty
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion_sensor
    to: 'off'
    for:
      minutes: 1
  condition:
    condition: and
    conditions:
      - condition: time
        after: '06:30:00'
        before: '23:00:00'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
        state: 'off'
      - condition: state
        entity_id: binary_sensor.sleepnumber_m7_liz_is_in_bed
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.bedroom
    data: 
      transition: 4
