- alias: ColemanInBed
  trigger:
    platform: state
    entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    to: 'on'
  action:
    service: notify.mypushbullet
    data_template:
      title: "Coleman Bed Sensor"
      message: "Coleman in bed"

- alias: ColemanOutBed
  trigger:
    platform: state
    entity_id: binary_sensor.sleepnumber_m7_coleman_is_in_bed
    to: 'off'
  action:
    service: notify.mypushbullet
    data_template:
      title: "Coleman Bed Sensor"
      message: "Coleman out of bed"


# slider automation of kitchen
- alias: Brightness Kitchen
  trigger:
    platform: state
    entity_id: input_number.brightness_kitchen
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.kitchen
    data_template:
      brightness: '{{ states( "input_number.brightness_kitchen" )|round( 0 ) }}'

# slider automation of bedroom
- alias: Brightness Bedroom
  trigger:
    platform: state
    entity_id: input_number.brightness_bedroom
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.bedroom
    data_template:
      brightness: '{{ states( "input_number.brightness_bedroom" )|round( 0 ) }}'