#THINGS I WANT TO ADD
# f.lux 
#     https://www.home-assistant.io/components/switch.flux/
# alerts for low battery on hue sensors or switches
#     https://www.home-assistant.io/components/alert/
# Open Hardware tracking of Pi performance and speeds and temps
#      https://www.home-assistant.io/components/sensor.openhardwaremonitor/
# better icons
#     https://materialdesignicons.com/

mqtt:
  broker: 192.168.0.111

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elev
  # metric for Metric, imperial for Imperial
  unit_system: Imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  # Customization file
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: https://whereintheworld.duckdns.org:8123
  ssl_certificate: /etc/letsencrypt/live/whereintheworld.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/whereintheworld.duckdns.org/privkey.pem
#  cors_allowed_origins:
#    - https://google.com
#    - https://www.home-assistant.io
#  use_x_forwarded_for: true
#  trusted_proxies:
#    - 127.0.0.1
#    - ::1
#  ip_ban_enabled: true
  login_attempts_threshold: 5

duckdns:
  domain: whereintheworld
  access_token: !secret duckdns_token

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Creates a history graph
history_graph:
  temperature:
    name: Temperature Graph
    entities:
      - sensor.living_room_thermostat_temperature
    hours_to_show: 72

# Enables configuration UI
config:

# reduces volume of recorder logfile
recorder:
  # Delete events and states older than 2 weeks
  purge_interval: 2
  purge_keep_days: 7


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: !secret node-red_url


# Discover some devices automatically
discovery:
  ignore:
    - sonos
    - samsung_tv
    - philips_hue
  enable:






# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

owntracks:

# CONTROLS
input_number: !include input-numbers.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Sleep Number SleepIQ
sleepiq:
  username: !secret primary_email
  password: !secret sn_pw

# dARK sKY api weather
weather:
  - platform: darksky
    api_key: !secret ds_api

# Nest
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_pw
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'operation_mode'

# Kasa / TP-Link Switches
tplink:
  switch:
    - host: !secret switch1_ip
    - host: !secret switch2_ip

# Components
hue:
  bridges: 
    - host: !secret hue_bridge_ip
      allow_unreachable: true
      allow_hue_groups: true

binary_sensor:
  - platform: hue_custom
device_tracker:
  - platform: hue_custom

sensor:
  # custom Hue Sensor (robmarkcole)
  - platform: hue_custom

  # Weather prediction
  - platform: yr

  # pihole
  - platform: pi_hole
    name: 'Pi Hole'
#    host:
#    location:
#    ssl:
#    verify_ssl:
    monitored_conditions:
      - ads_blocked_today
#      - ads_percentage_today
#      - dns_queries_today
      - domains_being_blocked
#      - queries_cached
#      - queries_forwarded
#      - unique_clients
#      - unique_domains
#      - clients_ever_seen

  # CPU speed
  - platform: cpuspeed

  # system monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use


  #hue hub #FIXME
#  - platform: hue
#    ip_address: 192.168.0.203
#    token: !secret hue_tkn

  #hue motion sensors #FIXME add the remainder of the variables
  - platform: template
    scan_interval: 0.5
    sensors:

      kitchen_sensor_battery:
        friendly_name: 'kitchen sensor battery'
        value_template: '{{state_attr("binary_sensor.kitchen_motion_sensor", "battery")}}'
        unit_of_measurement: percent

      kitchen_temperature:
        friendly_name: 'kitchen temperature'
        value_template: '{{state_attr("binary_sensor.kitchen_motion_sensor", "temperature")}}'
        unit_of_measurement: °C

      kitchen_light_level:
        friendly_name: 'kitchen light level'
        value_template: '{{state_attr("binary_sensor.kitchen_motion_sensor", "lx")}}'
        unit_of_measurement: lux

      bedroom_temperature:
        friendly_name: 'bedroom temperature'
        value_template: '{{state_attr("binary_sensor.bedroom_motion_sensor", "temperature")}}'
        unit_of_measurement: °C

      bedroom_sensor_battery:
        friendly_name: 'bedroom sensor battery'
        value_template: '{{state_attr("binary_sensor.bedroom_motion_sensor", "battery")}}'
        unit_of_measurement: percent

      bedroom_light_level:
        friendly_name: 'bedroom light level'
        value_template: '{{state_attr("binary_sensor.bedroom_motion_sensor", "lx")}}'
        unit_of_measurement: lux

      bedroom_time:
        friendly_name: 'bedroom time'
        value_template: '{{state_attr("binary_sensor.bedroom_motion_sensor", "last_updated")}}'
        unit_of_measurement: time

  - platform: template
    scan_interval: 1
    sensors:
      outside_temperature:
        friendly_name: 'Outside Temperature Dark Sky'
        unit_of_measurement: °F
        value_template: '{{states.weather.dark_sky.attributes.temperature}}'

  - platform: template
    sensors:
      num_in_master_bed:
        friendly_name: 'Number of People in Bed'
        unit_of_measurement: 'people'
        value_template: >-
          {% if is_state('binary_sensor.sleepnumber_m7_coleman_is_in_bed', 'on') and is_state('binary_sensor.sleepnumber_m7_liz_is_in_bed', 'on') %}
              3
          {% elif is_state('binary_sensor.sleepnumber_m7_coleman_is_in_bed', 'on') and is_state('binary_sensor.sleepnumber_m7_liz_is_in_bed', 'off') %}
              2
          {% elif is_state('binary_sensor.sleepnumber_m7_coleman_is_in_bed', 'off') and is_state('binary_sensor.sleepnumber_m7_liz_is_in_bed', 'on') %}          
              1
          {% else %}
              0
          {% endif %}

  - platform: template
    sensors:
      bed_occupied:
        friendly_name: "Is >=1 in Bed"
        unit_of_measurement: 'binary'
        value_template: >-
          {% if is_state('binary_sensor.sleepnumber_m7_coleman_is_in_bed', 'on') and is_state('binary_sensor.sleepnumber_m7_liz_is_in_bed', 'on') %}
              1
          {% elif is_state('binary_sensor.sleepnumber_m7_coleman_is_in_bed', 'on') or is_state('binary_sensor.sleepnumber_m7_liz_is_in_bed', 'on') %}
              1
          {% else %}
              0
          {% endif %}

#updater for custom hue sensors
custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json

# Pushbullet notify me of bed sensor
notify me:
  platform: pushbullet
  api_key: !secret push_api
  name: mypushbullet

#--------------------------------------------------

camera:
  - platform: generic
    still_image_url: 'https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=PBZ&brand=wui&num=10&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=0&rand=25525009&lat=0&lon=0&label=you'
    name: Radar