views:
  - title: main
    icon: mdi:home-outline
    cards:

    - type: glance
      title: Lights
      show_name: true
      show_state: true
      entities:
        - light.kitchen
        - light.bedroom


    - type: "custom:button-card"
      entity: switch.living_room_lamp
      icon: mdi:sofa
      color: auto
      name: Living room lamp

    - type: entities
      title: Sample
      show_header_toggle: true
      entities:
        - type: call-service
          icon: mdi:power
          name: Kitchen Light
          action_name: Toggle light
          service: light.toggle
          service_data:
            entity_id: light.kitchen
        - type: divider
        - type: weblink
          name: Old UI frontend
          url: http://192.168.0.111:8123/states
          icon: mdi:home-assistant